import { FilterOptions } from '../types/FilterType';

export const filterOptions: FilterOptions[] = [
  {
    id: 'opportunityType',
    nameOfFilter: 'opportunity type',
    value: ['Voluntary', 'Wishes'],
  },
  {
    id: 'assistanceType',
    nameOfFilter: 'type of help',
    value: ['Volunteering', 'Donation'],
  },
  {
    id: 'categoryName',
    nameOfFilter: 'category',
    value: [],
  },
  {
    id: 'location',
    nameOfFilter: 'location',
    value: [
      'Kyiv',
      'Kharkiv',
      'Odesa',
      'Dnipro',
      'Lviv',
      'Zaporizhzhia',
      'Mykolaiv',
      'Mariupol',
      'Vinnytsia',
      'Chernihiv',
      'Sumy',
      'Poltava',
      'Cherkasy',
      'Khmelnytskyi',
      'Rivne',
      'Ternopil',
      'Ivano-Frankivsk',
      'Zhytomyr',
      'Kirovohrad',
      'Luhansk',
      'Donetsk',
      'Chernivtsi',
      'Kherson',
      'Zakarpattia',
      'Lutsk',
      'Kremenchuk',
      'Online',
    ],
  },
  {
    id: 'startDate',
    nameOfFilter: 'start date',
    value: null,
  },
  {
    id: 'endDate',
    nameOfFilter: 'end date',
    value: null,
  },
];
