import { FilterOptions } from '../types/FilterType';

export const filterOptions: FilterOptions[] = [
  {
    id: 'opportunityType',
    nameOfFilter: 'opportunity type',
    value: ['Voluntary', 'Wishes'],
  },
  {
    id: 'assistanceType',
    nameOfFilter: 'type of help',
    value: ['Volunteering', 'Donation'],
  },
  {
    id: 'categoryName',
    nameOfFilter: 'category',
    value: [
      'Military Support',
      'Humanitarian Aid',
      'Medical Assistance',
      'Reconstruction & Infrastructure',
      'Mental Health',
      'Education & Mentorship',
      'Community & Local Initiatives',
      'Cultural & Historical Preservation',
    ],
  },
  {
    id: 'location',
    nameOfFilter: 'location',
    value: [
      'Kyiv',
      'Kharkiv',
      'Odesa',
      'Dnipro',
      'Lviv',
      'Zaporizhzhia',
      'Mykolaiv',
      'Mariupol',
      'Vinnytsia',
      'Chernihiv',
      'Sumy',
      'Poltava',
      'Cherkasy',
      'Khmelnytskyi',
      'Rivne',
      'Ternopil',
      'Ivano-Frankivsk',
      'Zhytomyr',
      'Kirovohrad',
      'Luhansk',
      'Donetsk',
      'Chernivtsi',
      'Kherson',
      'Zakarpattia',
      'Lutsk',
      'Kremenchuk',
      'Online',
    ],
  },
  {
    id: 'duration',
    nameOfFilter: 'time demands',
    value: [
      { '0-1': 'Up to 1 hour' },
      { '2-6': '1-6 hours' },
      { '7-24': 'Up to a day' },
      { '25-144': 'Up to a week' },
      { '145-744': 'Up to a month' },
      { '745-2232': '1 - 3 months' },
      { '2233-4464': '3 - 6 months' },
      { '4465-8950': 'Up to a year ' },
    ],
  },
  {
    id: 'startDate',
    nameOfFilter: 'start date',
    value: null,
  },
  {
    id: 'endDate',
    nameOfFilter: 'end date',
    value: null,
  },
];
