export type EventType = {
  "id": string,
  "title": string,
  "description": string,
  "opportunityType": string,
  "assistanceType": string,
  "categoryId": string,
  "categoryName": string,
  "location": string,
  "date": string,
  "duration": number,
  "image": string,
  "goal": number,
  "currentProgress": number,
}