export enum Path {
  Home = '/',
  Explore = '/explore',
  Volunteering = '/volunteering',
  Wishes = '/wishes',
  Donate = '/donate',
  HomeAI = '/ai',
  Response = '/response',
  Stories = '/stories',
  About = '/about-us',
  Faq = '/about-us/faq',
  Contact = '/contact',
  SignUp = '/sign-up',
  LogIn = '/log-in',
  Profile = '/profile',
  Menu = '/menu',
}
